services:
  postgres:
    image: postgres:latest
    container_name: gently-postgres
    restart: always
    environment:
      POSTGRES_USER: gently
      POSTGRES_PASSWORD: gently
      POSTGRES_DB: gently
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5832:5432"
    networks:
      - gently

  mailhog:
    container_name: gently-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - gently

volumes:
  postgres_data:

networks:
  gently:
    driver: bridge
