/**
 * Alarm utilities for calculating next occurrence, formatting times, etc.
 */

import { format, isAfter } from "date-fns";

/**
 * Generate a unique 10-character alphanumeric peripheral ID for an alarm
 * Used to verify alarm identity on the BLE device
 */
export function generatePeripheralId(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let result = "";
  for (let i = 0; i < 10; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

/**
 * Helper function to validate and log invalid dates
 */
function validateDate(date: Date, context: string): boolean {
  if (isNaN(date.getTime())) {
    console.warn(`Invalid date in ${context}:`, date);
    return false;
  }
  return true;
}

export interface AlarmScheduleInfo {
  nextOccurrence: Date | null;
  isOverdue: boolean;
  timeUntilNext: string;
  formattedNextTime: string;
  status: "active" | "inactive" | "overdue" | "completed";
}

/**
 * Calculate the next occurrence of an alarm based on its cron expression and date range
 */
export function calculateNextAlarmOccurrence(alarm: {
  isActive: boolean;
  startDate: Date;
  endDate: Date | null;
  repeat: boolean;
  cronExpression: string;
}): AlarmScheduleInfo {
  const now = new Date();

  // Validate start date
  if (
    !validateDate(alarm.startDate, "calculateNextAlarmOccurrence startDate")
  ) {
    return {
      nextOccurrence: null,
      isOverdue: false,
      timeUntilNext: "Invalid date",
      formattedNextTime: "Invalid date",
      status: "inactive",
    };
  }

  if (!alarm.isActive) {
    return {
      nextOccurrence: null,
      isOverdue: false,
      timeUntilNext: "Inactive",
      formattedNextTime: "Inactive",
      status: "inactive",
    };
  }

  // For non-repeating alarms
  if (!alarm.repeat) {
    const alarmTime = alarm.startDate;

    try {
      if (isAfter(now, alarmTime)) {
        return {
          nextOccurrence: null,
          isOverdue: true,
          timeUntilNext: "Overdue",
          formattedNextTime: formatAlarmTime(alarmTime, true),
          status: "overdue",
        };
      }

      return {
        nextOccurrence: alarmTime,
        isOverdue: false,
        timeUntilNext: formatTimeUntil(alarmTime),
        formattedNextTime: formatAlarmTime(alarmTime, true),
        status: "active",
      };
    } catch (error) {
      console.warn("Error processing non-repeating alarm:", error, alarmTime);
      return {
        nextOccurrence: null,
        isOverdue: false,
        timeUntilNext: "Invalid date",
        formattedNextTime: "Invalid date",
        status: "inactive",
      };
    }
  }

  // For repeating alarms, we need to parse the cron expression
  // This is a simplified implementation - in a real app you'd use a cron parser library
  try {
    const nextOccurrence = calculateNextCronOccurrence(
      alarm.cronExpression,
      alarm.startDate,
      alarm.endDate,
    );

    if (!nextOccurrence || isNaN(nextOccurrence.getTime())) {
      return {
        nextOccurrence: null,
        isOverdue: false,
        timeUntilNext: "Completed",
        formattedNextTime: "No future occurrences",
        status: "completed",
      };
    }

    return {
      nextOccurrence,
      isOverdue: false,
      timeUntilNext: formatTimeUntil(nextOccurrence),
      formattedNextTime: formatAlarmTime(nextOccurrence, true),
      status: "active",
    };
  } catch (error) {
    console.warn(
      "Error processing repeating alarm:",
      error,
      alarm.cronExpression,
    );
    return {
      nextOccurrence: null,
      isOverdue: false,
      timeUntilNext: "Invalid schedule",
      formattedNextTime: "Invalid schedule",
      status: "inactive",
    };
  }
}

/**
 * Calculate next occurrence based on cron expression
 * Handles the specific patterns generated by the app
 */
function calculateNextCronOccurrence(
  cronExpression: string,
  startDate: Date,
  endDate: Date | null,
): Date | null {
  // Validate input dates
  if (isNaN(startDate.getTime())) {
    console.warn(
      "Invalid start date in calculateNextCronOccurrence:",
      startDate,
    );
    return null;
  }

  if (endDate && isNaN(endDate.getTime())) {
    console.warn("Invalid end date in calculateNextCronOccurrence:", endDate);
    endDate = null;
  }

  const now = new Date();
  const parts = cronExpression.split(" ");

  if (parts.length !== 5) {
    console.warn("Invalid cron expression format:", cronExpression);
    return null;
  }

  const [minutePart, hourPart, dayPart, monthPart, dowPart] = parts;

  // Case 1: Daily repeating alarm (e.g., "30 7 * * *" - every day at 7:30)
  if (
    dayPart === "*" &&
    monthPart === "*" &&
    dowPart === "*" &&
    !hourPart?.startsWith("*/") &&
    !minutePart?.startsWith("*/")
  ) {
    const minute = parseInt(minutePart ?? "0", 10);
    const hour = parseInt(hourPart ?? "0", 10);

    if (isNaN(minute) || isNaN(hour)) {
      console.warn("Invalid hour/minute in daily cron:", cronExpression);
      return null;
    }

    // Try today first
    const candidate = new Date();
    candidate.setHours(hour, minute, 0, 0);

    if (candidate > now && candidate >= startDate) {
      if (!endDate || candidate <= endDate) {
        return candidate;
      }
    }

    // Try tomorrow
    const tomorrow = new Date(candidate);
    tomorrow.setDate(tomorrow.getDate() + 1);

    if (tomorrow >= startDate && (!endDate || tomorrow <= endDate)) {
      return tomorrow;
    }

    return null;
  }

  // Case 2: Weekly repeating alarm (e.g., "0 8 * * 1,2,3,4,5" - weekdays at 8:00)
  if (
    dayPart === "*" &&
    monthPart === "*" &&
    dowPart !== "*" &&
    !hourPart?.startsWith("*/")
  ) {
    const minute = parseInt(minutePart ?? "0", 10);
    const hour = parseInt(hourPart ?? "0", 10);
    const allowedDays =
      dowPart?.split(",").map((d) => parseInt(d.trim(), 10)) ?? [];

    if (isNaN(minute) || isNaN(hour) || allowedDays.some(isNaN)) {
      console.warn("Invalid weekly cron expression:", cronExpression);
      return null;
    }

    // Check the next 7 days
    for (let i = 0; i < 7; i++) {
      const candidate = new Date();
      candidate.setDate(candidate.getDate() + i);
      candidate.setHours(hour, minute, 0, 0);

      const dayOfWeek = candidate.getDay();

      if (
        allowedDays.includes(dayOfWeek) &&
        candidate > now &&
        candidate >= startDate
      ) {
        if (!endDate || candidate <= endDate) {
          return candidate;
        }
      }
    }

    return null;
  }

  // Case 3: Every X minutes (e.g., "*/15 * * * *" - every 15 minutes)
  if (
    minutePart?.startsWith("*/") &&
    hourPart === "*" &&
    dayPart === "*" &&
    monthPart === "*" &&
    dowPart === "*"
  ) {
    const interval = parseInt(minutePart.substring(2), 10);

    if (isNaN(interval) || interval <= 0 || interval > 59) {
      console.warn("Invalid minute interval:", minutePart);
      return null;
    }

    // For minute-based repeating alarms, calculate from current time
    // The startDate is only used to determine when the alarm becomes active
    const searchFrom = startDate > now ? startDate : now;
    const candidate = new Date(searchFrom);
    const currentMinute = candidate.getMinutes();
    const nextMinute = Math.ceil((currentMinute + 1) / interval) * interval;

    if (nextMinute >= 60) {
      candidate.setHours(candidate.getHours() + 1);
      candidate.setMinutes(nextMinute % 60, 0, 0);
    } else {
      candidate.setMinutes(nextMinute, 0, 0);
    }

    // Only check endDate, not startDate (since we already used it above)
    if (!endDate || candidate <= endDate) {
      return candidate;
    }

    return null;
  }

  // Case 4: Every X hours (e.g., "30 */6 * * *" - every 6 hours at :30)
  if (
    hourPart?.startsWith("*/") &&
    dayPart === "*" &&
    monthPart === "*" &&
    dowPart === "*"
  ) {
    const interval = parseInt(hourPart.substring(2), 10);
    const minute = parseInt(minutePart ?? "0", 10);

    if (isNaN(interval) || isNaN(minute) || interval <= 0 || interval > 24) {
      console.warn("Invalid hour interval:", hourPart);
      return null;
    }

    // For hour-based repeating alarms, calculate from current time or startDate
    const searchFrom = startDate > now ? startDate : now;
    const candidate = new Date(searchFrom);
    candidate.setMinutes(minute, 0, 0);

    // If we've passed the minute mark this hour, move to next interval
    if (candidate <= searchFrom) {
      candidate.setHours(candidate.getHours() + 1);
    }

    // Round up to next interval
    const currentHour = candidate.getHours();
    const nextHour = Math.ceil(currentHour / interval) * interval;

    if (nextHour >= 24) {
      candidate.setDate(candidate.getDate() + Math.floor(nextHour / 24));
      candidate.setHours(nextHour % 24, minute, 0, 0);
    } else {
      candidate.setHours(nextHour, minute, 0, 0);
    }

    // Only check endDate
    if (!endDate || candidate <= endDate) {
      return candidate;
    }

    return null;
  }

  // Case 5: Every X days (e.g., "0 9 */3 * *" - every 3 days at 9:00)
  if (dayPart?.startsWith("*/") && monthPart === "*" && dowPart === "*") {
    const interval = parseInt(dayPart.substring(2), 10);
    const minute = parseInt(minutePart ?? "0", 10);
    const hour = parseInt(hourPart ?? "0", 10);

    if (isNaN(interval) || isNaN(minute) || isNaN(hour) || interval <= 0) {
      console.warn("Invalid day interval:", dayPart);
      return null;
    }

    // Start from today or startDate, whichever is later
    const searchStart = startDate > now ? startDate : now;
    const candidate = new Date(searchStart);
    candidate.setHours(hour, minute, 0, 0);

    // If time has passed today, start from tomorrow
    if (candidate <= now) {
      candidate.setDate(candidate.getDate() + 1);
    }

    // Calculate days since startDate
    const daysSinceStart = Math.floor(
      (candidate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24),
    );

    // Adjust to next interval
    const remainder = daysSinceStart % interval;
    if (remainder !== 0) {
      candidate.setDate(candidate.getDate() + (interval - remainder));
    }

    if (candidate >= startDate && (!endDate || candidate <= endDate)) {
      return candidate;
    }

    return null;
  }

  // Case 6: One-time alarm (specific date and time, e.g., "30 14 25 10 *")
  if (
    !minutePart?.includes("*") &&
    !hourPart?.includes("*") &&
    !dayPart?.includes("*") &&
    !monthPart?.includes("*")
  ) {
    const minute = parseInt(minutePart ?? "0", 10);
    const hour = parseInt(hourPart ?? "0", 10);
    const day = parseInt(dayPart ?? "1", 10);
    const month = parseInt(monthPart ?? "1", 10);

    if (isNaN(minute) || isNaN(hour) || isNaN(day) || isNaN(month)) {
      console.warn("Invalid one-time cron:", cronExpression);
      return null;
    }

    // This is handled by the non-repeating alarm logic, but we can construct the date here too
    const candidate = new Date(startDate);
    candidate.setMonth(month - 1, day);
    candidate.setHours(hour, minute, 0, 0);

    if (candidate > now && (!endDate || candidate <= endDate)) {
      return candidate;
    }

    return null;
  }

  console.warn("Unsupported cron pattern:", cronExpression);
  return null;
}

/**
 * Format time until next occurrence in a human-readable way
 */
function formatTimeUntil(targetDate: Date): string {
  // Validate the target date
  if (isNaN(targetDate.getTime())) {
    console.warn("Invalid target date in formatTimeUntil:", targetDate);
    return "Invalid time";
  }

  const now = new Date();
  let diffMs: number;

  try {
    diffMs = targetDate.getTime() - now.getTime();
  } catch (error) {
    console.warn("Error calculating time difference:", error);
    return "Invalid time";
  }

  if (diffMs <= 0) {
    return "Now";
  }

  const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  const hours = Math.floor((diffMs % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  const minutes = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));

  if (days > 0) {
    return `${days}d ${hours}h`;
  } else if (hours > 0) {
    return `${hours}h ${minutes}m`;
  } else {
    return `${minutes}m`;
  }
}

/**
 * Get status color for alarm based on its state
 */
export function getAlarmStatusColor(scheduleInfo: AlarmScheduleInfo): string {
  switch (scheduleInfo.status) {
    case "active":
      return "#10b981"; // green
    case "inactive":
      return "#6b7280"; // gray
    case "overdue":
      return "#ef4444"; // red
    case "completed":
      return "#6b7280"; // gray
    default:
      return "#6b7280";
  }
}

/**
 * Format alarm time for display
 */
export function formatAlarmTime(date: Date, includeDate = true): string {
  // Validate the date before formatting
  if (isNaN(date.getTime())) {
    console.warn("Invalid date in formatAlarmTime:", date);
    return "Invalid date";
  }

  try {
    if (includeDate) {
      return format(date, "MMM dd, h:mm a");
    }
    return format(date, "h:mm a");
  } catch (error) {
    console.warn("Error formatting alarm time:", error, date);
    return "Invalid date";
  }
}
