export const tokens = {
  color: {
    cyan: "#16BCE9",
    cyanDeep: "#0E8FB6",
    cyanBg: "#E4F5FB",
    cyanBgSoft: "#F1FAFD",
    inkH: "#0C141C",
    ink: "#1A222C",
    ink2: "#4E5A68",
    ink3: "#8390A0",
    bg: "#F2F4F7",
    bgDeep: "#E6EAF0",
    card: "#FFFFFF",
    rule: "rgba(12,20,28,0.06)",
    rule2: "rgba(12,20,28,0.10)",
    amber: "#C07A1C",
    amberBg: "#FAEBD3",
    coral: "#C24A4A",
    coralBg: "#F8DCD9",
    led: {
      blue: "#3D6FE8",
      green: "#4FB36D",
      cyan: "#2BB5E0",
      red: "#E25C5C",
      yellow: "#EAD24A",
      magenta: "#C45EC0",
      white: "#F5F5F5",
    },
  },
  radius: {
    card: 20,
    cardLarge: 24,
    list: 18,
    cta: 16,
    pill: 999,
  },
  spacing: {
    pageHorizontal: 18,
    contentHorizontal: 24,
    section: 22,
    cardInternal: 16,
  },
  shadow: {
    card: {
      shadowColor: "#0C141C",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 1,
    },
    hover: {
      shadowColor: "#0C141C",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 3,
    },
    primary: {
      shadowColor: "#16BCE9",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.28,
      shadowRadius: 22,
      elevation: 4,
    },
  },
  font: {
    weightStrong: "700",
    weightMedium: "500",
    weightLight: "300",
  },
} as const;
